import type { Metadata } from "next";
import "../styles/global-style";
import Tabbar from "./components/layouts/Tabbar";
import Header from "./components/layouts/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <div className="container">
          <Header />
          <main>{children}</main>
          <Tabbar />
        </div>
      </body>
    </html>
  );
}
