import type { Metadata } from "next";
import type { Viewport } from "next";
import "../styles/global-style";
import ReduxProvider from "./ReduxProvider";

export const metadata: Metadata = {
  title: "WEEKLY-PLAN",
  description: "Generated by create next app",
  icons: {
    icon: "/imgs/favicon/favicon.ico",
    apple: "/imgs/favicon/apple-touch-icon.png",
  },
  manifest: "/imgs/favicon/site.webmanifest",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  viewportFit: "cover",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <ReduxProvider>
        <body>
          <div className="container">{children}</div>
        </body>
      </ReduxProvider>
    </html>
  );
}
