import type { Metadata } from "next";
import type { Viewport } from "next";
import "../styles/global-style";
import ReduxProvider from "./ReduxProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  viewportFit: "cover",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <ReduxProvider>
        <body>
          <div className="container">{children}</div>
        </body>
      </ReduxProvider>
    </html>
  );
}
