export const menuList = [
  {
    menu: "TODO",
    href: "/",
    srcTab: "/imgs/icons/tabbar/new/todo.svg",
    srcTabActive: "/imgs/icons/tabbar/new/todo_active.svg",
    srcSide: "/imgs/icons/sidebar/ic_todo-24.svg",
    srcSideActive: "/imgs/icons/sidebar/ic_todo_active-24.svg",
    alt: "투두메뉴",
  },
  {
    menu: "일기",
    href: "/diary",
    srcTab: "/imgs/icons/tabbar/new/diary.svg",
    srcTabActive: "/imgs/icons/tabbar/new/diary_active.svg",
    srcSide: "/imgs/icons/sidebar/ic_diary-24.svg",
    srcSideActive: "/imgs/icons/sidebar/ic_diary_active-24.svg",
    alt: "주간일기",
  },
  {
    menu: "달력",
    href: "/calendar",
    srcTab: "/imgs/icons/tabbar/new/calendar.svg",
    srcTabActive: "/imgs/icons/tabbar/new/calendar_active.svg",
    srcSide: "/imgs/icons/sidebar/ic_calendar-24.svg",
    srcSideActive: "/imgs/icons/sidebar/ic_calendar_active-24.svg",
    alt: "달력보기",
  },
  {
    menu: "내페이지",
    href: "/mypage",
    srcTab: "/imgs/icons/tabbar/ic_user-24.svg",
    srcTabActive: "/imgs/icons/tabbar/ic_user-24_active.svg",
    srcSide: "/imgs/icons/sidebar/ic_user-24.svg",
    srcSideActive: "/imgs/icons/sidebar/ic_user_active-24.svg",
    alt: "투두메뉴",
  },
];
